In [1]:
import cv2
import numpy as np

In [2]:
img = cv2.imread('photo5.jpg',1)
img = cv2.resize(img,(img.shape[0]*8,img.shape[1]*3))

In [3]:
print(img.shape)

(897, 1344, 3)


In [4]:
cv2.imshow('photo',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
img2 = img.copy()

In [6]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [7]:
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [8]:
face_coord = face_cascade.detectMultiScale(gray,scaleFactor=1.1,minNeighbors = 5)

In [9]:
print(face_coord)

[[1210  166   99   99]
 [1071  175   85   85]
 [ 244  224   85   85]
 [ 785  201   73   73]
 [ 907  203   81   81]
 [ 433  206   80   80]
 [ 611  206   79   79]
 [  75  189  106  106]]


In [10]:
face_dims = []
for x,y,w,h in face_coord:
    face_dims.append((w,h))
print(face_dims)

[(99, 99), (85, 85), (85, 85), (73, 73), (81, 81), (80, 80), (79, 79), (106, 106)]


In [11]:
for x,y,w,h in face_coord:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),1)

In [12]:
cv2.imshow('faces',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
blank_dim = (max([face_dims[i][1] for i in range(len(face_dims))])+5,sum([face_dims[i][0] for i in range(len(face_dims))])+5)

In [14]:
blank_dim

(111, 693)

In [15]:
mat = np.zeros(blank_dim)

In [16]:
cv2.imwrite('blankscreen.jpg',mat)
mat = cv2.imread('blankscreen.jpg',1)

In [17]:
i = j = 0
for x,y,w,h in face_coord:    
    for a in range(x,x+w):
        j = 0
        for b in range(y,y+h):
            mat[j,i] = img2[b-1,a-1]
            j = j+1
        i = i+1

In [18]:
cv2.imshow('cropped',mat)
cv2.waitKey(0)
cv2.destroyAllWindows()